




.build/uno/src/AutonomousSailboat-v0.1.cpp : src/AutonomousSailboat-v0.1.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/AutonomousSailboat-v0.1.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/AutonomousSailboat-v0.1.cpp
	@true

